name: pytest-unit-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: unit testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout simple_functions
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools -y
        pip3 install --upgrade pip
        pip3 install -e .
        pip3 install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest tests/
